language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements-dev.txt

script:
  - py.test --pep8 sevenbridges --cov sevenbridges
  - flake8 sevenbridges

deploy:
  provider: pypi
  user: sbg
  password:
    secure: SHbkHQffX62kJIU4Kp2JqcqyQ1FJV1XUVltsCbo51pedKCdbqSTC77M9AvYtXU07rK/l8U0mw3gaNwWW8npbQKVZZLyPUtLG3sx8FG1V9zbEpP9lYcOuysuDf/AjL4iQquWNUewa/6nYeW005YX+bguHINCLean97WcW4e0YC2OY2BKPRIoDwBLPyRoUS+nYMTTr8NWPzkdEDXakieEk6KpfaqoK9NfGk8SWRhgI03mDi1WyUeqRdqAjTkDPCUzdzY25g8Jk/k8f2iqZ4O4MarWO0b6l4Kbb8oLVXDk/r0aJBBGPhAOigdBreX2YzmJrxF/UlWdVd3AAFTGldqlsMUCc7ARcKmfnGYCm/oKEmstS7C2TWtTaOofiMO1YWrt6h2LyMX+G2YwyNFknV6Pe5sYX2JQUbq1HJf4sWa123au63OZUqTSQ7lKK7U8RI39zA4N9XQUuHf3TFWNejiDvGxOES/CXJMpbo0vD1qa0Y9tti6lLpAtT+1kIh4MzvjVeGtWts+KzfPyAsP3AGlAep6/+TTqxhnnWvcDvnBA2C22/Iw2Gur4nX0gNO81vId1xk5eEN31nYRXHUPYp+oBmC2fcIMxCArQHr7cgQbmW2PBnTaQgNQzML20z1Yv/tTOl3I3RwpKb2r+dWWmU1rO4ERc66V470ChH5Px9s9coZZ4=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-python
